// example
export const CHANGELOGINSTATUES = 'CHANGELOGINSTATUES'

// control dialog of select store visible

export const CHANGESELECTSTOREDIALOG = 'CHANGESELECTSTOREDIALOG'

export const CHANGESTOREINFO = 'CHANGESTOREINFO'

export const CHANGETECHINFO = 'CHANGETECHINFO';

export const CHANGESERVERINFO= 'CHANGESERVERINFO';

export const CHANGETITLE= 'CHANGETITLE';

export const CHANGESTORELIST= 'CHANGESTORELIST';

export const CHANGELOGININFO= 'CHANGELOGININFO';

export const CHANGEISLOGIN='CHANGEISLOGIN';

export const CHANGEMENUINDEX='CHANGEMENUINDEX';

export const CHANGEHEADMENUINDEX = 'CHANGEHEADMENUINDEX'
